- hosts: student
  become: true
  tasks:
   - name: Install Gitlab's deps
     apt: name=apache2 update_cache=yes state=latest
     apt: name=curl update_cache=yes state=latest
     apt: name=openssh-server update_cache=yes state=latest
     apt: name=ca-certificates update_cache=yes state=latest
     apt: name=postfix update_cache=yes state=latest

   - name: download Gitlab script
     get_url: url=https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh dest=/opt/
#mode=777

# Disabled for 20.04 
#   - name: execute script
#     script: /opt/script.deb.sh

   - name: install gitlab
     apt: name=gitlab-ce update_cache=yes state=latest

   - name: configure gitlab external url
     replace:
       path: /etc/gitlab/gitlab.rb
       regexp: "external_url 'http://gitlab.example.com'" 
       replace: external_url 'http://gitlab.student.local'

   - name: Configure nginx listen addresses
     lineinfile:
       path: /etc/gitlab/gitlab.rb
       regexp: "^(\\#)?nginx\\['listen_addresses'\\].*$"
       line: "nginx['listen_addresses'] = ['localhost']"

   - name: Configure nginx listen port
     lineinfile:
       path: /etc/gitlab/gitlab.rb
       regexp: "^(\\#)?nginx\\['listen_port'\\].*$"
       line: "nginx['listen_port'] = 8888"

   - name: Configure nginx https
     lineinfile:
       path: /etc/gitlab/gitlab.rb
       regexp: "^(\\#)?nginx\\['listen_https'\\].*$"
       line: "nginx['listen_https'] = false"

   - name: "Launch Gitlab's reconfigure"
     command: gitlab-ctl reconfigure
